version: '3'

services:
  backend:
    build:
      context: ./DocManagement
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations && 
             python manage.py migrate &&
             gunicorn MyProject.wsgi --bind 0.0.0.0:8000 --timeout 1000"
    volumes:
      - static_volume:/DocManagement/staticfiles
      - media_volume:/DocManagement/AllImages
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  
  mongodb:
    environment:
      MONGO_INITDB_DATABASE: DocManagement
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    hostname: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: 
      - data-mongodb:/data/db


    
  frontend:
    build:
      context: ./material-kit-react
    volumes:
      - react_build:/material-kit-react/build
    ports:
      - "3000:3000"
    stdin_open: true


  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/material-kit-react
      - static_volume:/var/www/staticfiles
      - media_volume:/var/www/media
    depends_on:
      - backend
      - frontend
      - mongodb
volumes:
  react_build:
  static_volume:
  media_volume:
  data-mongodb: